services:
  api:
    build: .
    container_name: vetinhouse-backend
    ports:
      - "${PORT}:${PORT}"  # Mismo puerto dentro y fuera
    volumes:
      - .:/app  # WORKDIR es /app ahora
      - /app/node_modules  # Evita sobrescribir node_modules del contenedor
    environment:
      PORT: ${PORT}
      SUPPORTED_DATABASE: ${SUPPORTED_DATABASE}
      NODE_ENV: ${NODE_ENV}
      DATABASE_DIALECT: ${DATABASE_DIALECT}
      DATABASE_URI: ${DATABASE_URI}
    env_file:
      - .env  # Carga automáticamente todas las variables
    tty: true  # Habilita TTY para logs en tiempo real
    stdin_open: true
    restart: unless-stopped
    command: npm run dev  # Puedes sobrescribir el CMD aquí también